const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';

const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_ERROR = 'GET_USERS_ERROR';

const OPEN_MODAL_PHOTO = 'OPEN_MODAL_PHOTO';
const CLOSE_MODAL_PHOTO = 'CLOSE_MODAL_PHOTO';

export {
    GET_PHOTOS_REQUEST, 
    GET_PHOTOS_SUCCESS,
    GET_PHOTOS_ERROR,

    GET_USERS_REQUEST, 
    GET_USERS_SUCCESS,
    GET_USERS_ERROR,

    OPEN_MODAL_PHOTO,
    CLOSE_MODAL_PHOTO
};