const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_ERROR = 'GET_ERROR';

const OPEN_MODAL_PHOTO = 'OPEN_MODAL_PHOTO';
const CLOSE_MODAL_PHOTO = 'CLOSE_MODAL_PHOTO';

export {
    GET_REQUEST, 
    GET_SUCCESS,
    GET_ERROR,

    OPEN_MODAL_PHOTO,
    CLOSE_MODAL_PHOTO
};